import { expect, test } from "@playwright/test";
import { createAlbumActivityFixture } from "../../.tests/helpers/albumActivityFixture.js";

let fixture;
test.beforeAll(async () => { fixture = await createAlbumActivityFixture(); });
test.afterAll(async () => { await fixture?.stop(); });

test("album-grab rows preserve track controls and survive polling, search, restart, and cleanup", async ({ page }, testInfo) => {
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  const baseUrl = `http://127.0.0.1:${fixture.port}`;
  await page.goto(baseUrl);
  await page.getByLabel("Username").fill(fixture.username);
  await page.getByLabel("Password", { exact: true }).fill(fixture.password);
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page.getByLabel("Primary navigation")).toBeVisible();
  await page.goto(`${baseUrl}/activity/queue`);
  const flatRequests = await page.evaluate(async () => {
    const token = localStorage.getItem("auth_token") || sessionStorage.getItem("auth_token");
    const response = await fetch("/api/requests", { headers: { Authorization: `Bearer ${token}` } });
    if (!response.ok) throw new Error(`Requests returned ${response.status}`);
    return response.json();
  });
  const albumTracks = flatRequests.filter((item) => item.albumName === "Everything Now");
  expect(albumTracks).toHaveLength(13);
  expect(albumTracks.every((item) => item.kind === "track_download" && item.jobId && item.albumGrab)).toBe(true);
  const album = page.getByRole("region", { name: "Everything Now, Arcade Fire" });
  await expect(album).toBeVisible();
  await expect(album.getByText("Downloading album · 0 of 13 tracks ready")).toBeVisible();
  const expand = album.getByRole("button", { name: "Expand Everything Now", exact: true });
  await expect(expand).toHaveCSS("display", "flex");
  await expand.focus();
  await page.keyboard.press("Enter");
  const collapse = album.getByRole("button", { name: "Collapse Everything Now", exact: true });
  await expect(collapse).toHaveAttribute("aria-expanded", "true");
  await expect(album.getByRole("group", { name: "Album tracks" }).locator(".activity-row")).toHaveCount(13);
  await page.getByRole("button", { name: "Refresh activity" }).click();
  await expect(collapse).toHaveAttribute("aria-expanded", "true");
  await collapse.click();
  await page.getByRole("button", { name: "Filter activity" }).click();
  await page.getByRole("searchbox", { name: "Filter activity" }).fill("Put Your Money on Me");
  await expect(collapse).toBeVisible();
  await expect(album.getByRole("group", { name: "Album tracks" }).locator(".activity-row")).toHaveCount(13);
  await page.getByRole("button", { name: "Clear filter" }).click();

  const partial = page.getByRole("region", { name: "Partial album, Disposable Artist" });
  await partial.getByRole("button", { name: "Expand Partial album", exact: true }).click();
  await expect(partial.getByRole("button", { name: "Approve track", exact: true })).toBeVisible();
  await expect(partial.getByRole("button", { name: "Deny track", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Expand Track-only album" })).toHaveCount(0);
  await expect(page.getByRole("link", { name: "Open Individual first, Disposable Artist · Track-only album", exact: true })).toBeVisible();
  await expect(page.getByRole("link", { name: "Open Individual second, Disposable Artist · Track-only album", exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("album-grab-queue.png"), fullPage: true });

  await fixture.completeAlbum();
  await page.goto(`${baseUrl}/activity/history`);
  const completed = page.getByRole("region", { name: "Everything Now, Arcade Fire" });
  await expect(completed).toBeVisible();
  await expect(completed.getByText("Completed · 13 of 13 tracks ready")).toBeVisible();
  await completed.getByRole("button", { name: "Expand Everything Now", exact: true }).click();
  await expect(completed.getByRole("group", { name: "Album tracks" }).locator(".activity-row")).toHaveCount(13);
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(completed.getByText("Completed · 13 of 13 tracks ready")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath("album-grab-mobile.png"), fullPage: true });
  const albumInfo = completed.locator(":scope > .activity-row").getByRole("button", { name: "Show Everything Now details", exact: true });
  await albumInfo.click();
  const dialog = page.getByRole("dialog");
  await expect(dialog.getByText("Soulseek", { exact: true })).toBeVisible();
  await expect(dialog.getByText("Album download", { exact: true })).toHaveCount(2);
  await expect(dialog.getByText("Requested", { exact: true })).toBeVisible();
  await expect(dialog.locator("dt").filter({ hasText: /^Completed$/ })).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(dialog).toHaveCount(0);
  await expect(albumInfo).toBeFocused();
  await page.evaluate(() => localStorage.setItem("aurralTheme", "light"));
  await page.reload();
  await completed.getByRole("button", { name: "Expand Everything Now", exact: true }).click();
  await expect(completed.getByText("Completed · 13 of 13 tracks ready")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath("album-grab-mobile-light.png"), fullPage: true });
  expect(errors).toEqual([]);
});
