import { QueryClient } from "@tanstack/react-query";

const LIBRARY_CANONICAL_QUERY_KEY = ["library", "canonical"];
const LIBRARY_VIEW_QUERY_KEY = ["library", "view"];
const LIBRARY_ALBUM_TRACKS_QUERY_KEY = ["library", "tracks"];
let libraryCanonicalGeneration = 0;

export const bumpLibraryCanonicalGeneration = () => {
  libraryCanonicalGeneration += 1;
};

export const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      gcTime: typeof window === "undefined" ? Infinity : 5 * 60 * 1000,
      refetchOnReconnect: false,
      refetchOnWindowFocus: false,
      retry: 0,
      staleTime: 30 * 1000,
    },
  },
});

export const queryKeys = {
  authBootstrap: ["auth", "bootstrap"],
  discovery: (userId) => ["discovery", "home", userId || null],
  discoveryStatusPrefix: ["discovery", "status"],
  discoveryStatus: (userId) => ["discovery", "status", userId || null],
  editorialShelf: (userId) => ["discovery", "editorial", "shelf", userId || null],
  editorialPlaylist: (userId, playlistId) => ["discovery", "editorial", "playlist", userId || null, playlistId],
  appHealth: ["app", "health"],
  appSettings: ["settings", "app"],
  playbackSettings: ["settings", "playback"],
  downloadClientSettings: ["settings", "download-clients"],
  lidarrRootFolders: (url, credentialsRevision = 0) => [
    "settings",
    "lidarr",
    "root-folders",
    url || "",
    credentialsRevision,
  ],
  lidarrProfiles: (url, credentialsRevision = 0) => [
    "settings",
    "lidarr",
    "profiles",
    url || "",
    credentialsRevision,
  ],
  lidarrMetadataProfiles: (url, credentialsRevision = 0) => [
    "settings",
    "lidarr",
    "metadata-profiles",
    url || "",
    credentialsRevision,
  ],
  lidarrTags: (url, credentialsRevision = 0) => [
    "settings",
    "lidarr",
    "tags",
    url || "",
    credentialsRevision,
  ],
  activityRequests: (userId) => ["activity", "requests", userId || null],
  libraryActivityRequests: (userId) => ["library", "activity-requests", userId || null],
  inbox: (userId, zip, limit) => ["inbox", userId || null, zip || "", limit],
  listeningHistory: (userId) => ["auth", "listening-history", userId || null],
  lidarrPreferences: (userId) => ["auth", "lidarr-preferences", userId || null],
  libraryPrefix: ["library"],
  libraryFavorites: ["library", "favorites"],
  libraryAlbums: (artistId) => ["library", "albums", artistId || null],
  libraryAlbumsPrefix: ["library", "albums"],
  libraryArtist: (mbid) => ["library", "artist", mbid || null],
  artistMonitoring: (mbid) => ["library", "artist", mbid || null, "monitoring"],
  libraryLookupDetails: (mbid) => ["library", "lookup-details", mbid || null],
  libraryView: (options) => [...LIBRARY_VIEW_QUERY_KEY, options],
  libraryLookup: (id) => ["library", "lookup", id],
  libraryLookupBatch: (ids) => ["library", "lookup-batch", [...ids].sort()],
  libraryViewPrefix: LIBRARY_VIEW_QUERY_KEY,
  libraryCanonicalPrefix: LIBRARY_CANONICAL_QUERY_KEY,
  libraryCanonical: (options) => [
    ...LIBRARY_CANONICAL_QUERY_KEY,
    libraryCanonicalGeneration,
    options,
  ],
  libraryAlbumLookup: (ids) => ["library", "album-lookup", [...ids].sort()],
  libraryAlbumLookupPrefix: ["library", "album-lookup"],
  libraryAlbumTracksPrefix: LIBRARY_ALBUM_TRACKS_QUERY_KEY,
  libraryAlbumTracks: (albumId, releaseGroupMbid) => [
    ...LIBRARY_ALBUM_TRACKS_QUERY_KEY,
    albumId,
    releaseGroupMbid || null,
  ],
  nearbyShows: (zip, country) => ["shows", "nearby", zip || null, country || null],
  recentlyAdded: (userId) => ["library", "recently-added", userId || null],
  recentReleases: (userId) => ["library", "recent-releases", userId || null],
  news: (userId, mode, limit) => ["news", "library", userId || null, mode, limit],
  playlistStatus: ["playlists", "status"],
  flowTemplates: (userId) => ["playlists", "flow-templates", userId || null],
  playlistJobs: (flowId) => ["playlists", "jobs", flowId || "all"],
  playlistArtworkRevisions: ["playlists", "artwork-revisions"],
  releaseGroupDetails: (id) => ["artists", "release-group", id],
  releaseGroupTracks: (id, context) => ["artists", "release-group-tracks", id, context],
  releaseGroupRatings: (ids) => ["artists", "release-group-ratings", [...ids].sort()],
  artistDetails: (mbid, options = {}) => [
    "artists",
    "details",
    mbid || null,
    options.artistName || "",
    options.mode || "",
    Array.isArray(options.releaseTypes) ? options.releaseTypes : [],
    options.appearsOnLimit || null,
  ],
  artistDetailsPrefix: ["artists", "details"],
  artistOverrides: (mbid) => ["artists", "overrides", mbid || null],
  artistSimilar: (mbid, artistName, limit) => [
    "artists",
    "similar",
    mbid || null,
    artistName || "",
    limit,
  ],
  artistSimilarPrefix: ["artists", "similar"],
  artistAppearsOn: (mbid) => ["artists", "appears-on", mbid || null],
  activeDownloads: ["downloads", "active"],
  downloadStatus: (ids) => ["library", "download-status", [...ids].sort()],
  aurralAlbumStatus: (canonicalId) => ["library", "aurral-album-status", String(canonicalId)],
  searchCatalog: (query, scope, options) => ["search", scope, query, options],
  searchDiscovery: (offset, limit) => ["search", "discovery", offset || 0, limit || null],
  searchUnified: (query, mode, limit) => ["search", "unified", query, mode, limit],
  searchLibrary: (query, limit) => ["search", "library", query, limit],
  storageHealth: ["settings", "storage-health"],
  settingsTasks: ["settings", "tasks"],
  prowlarrIndexers: ["settings", "prowlarr-indexers"],
  tasteFeedback: (userId) => ["discovery", "feedback", userId],
  users: ["auth", "users"],
};
